namespace: aprenda-golang

api:  
  replicas: 3
  image_version: v1.1.0
  host: api.aprendendo-k8s.dev
  port: 8000  
  svc:
   name: api
   port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "512Mi"

services:
  - app: api    
    port: 80
    targetPort: 8000
  - app: redis
    port: 6379
    targetPort: 6379

redis:
  image_version: latest
  # host: redis.aprenda-golang.svc.cluster.local
  port: 6379
  replicas: 1
  secrets:
    password: "MTIzNA=="