common:
  app: api
  port: 8000
  namespace: aprenda-golang
  image_version: v1.1.0
  replicas: 3
  host: api.aprendendo-k8s.dev
  svc:
   name: api
   port: 80


resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "100m"
    memory: "512Mi"


configmap:
  server:
    port: "8000"
  redis:
    host: "redis.aprenda-golang.svc.cluster.local"
    port: 6379

services:
  - app: api    
    port: 80
    targetPort: 8000
  - app: redis
    port: 6379
    targetPort: 6379

redis:
  name: redis
  image_version: latest
  port: 6379
  replicas: 1
  secrets:
    password: "MTIzNA=="