version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - api.env
    volumes:
      - .:/app-config
    ports:
      - 8000:8000
    depends_on:
      - redis
  
  redis:
    image: redis
    ports:
      - 6379:6379