apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.common.app }}-cm
  namespace: {{ .Values.common.namespace }}
data:
  SERVER_PORT: {{ .Values.configmap.server.port }}
  REDIS_HOST: {{ .Values.configmap.redis.host }}
  REDIS_PORT: {{ .Values.configmap.redis.port }}