apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.app }}-cm
  namespace: {{ .Values.namespace }}
data:
  SERVER_PORT: {{ .Values.configmap.server.port }}
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PORT: {{ .Values.redis.port }}