apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.api.app }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.api.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.app }}
    spec:
      containers:
        - name: {{ .Values.api.app }}
          image: dexfs/my-api:{{ .Values.api.image_version }}
          ports:
            - containerPort: {{  .Values.api.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.api.app}}-cm
            - secretRef:
                name: {{ .Values.redis.name }}
          resources:
            requests:
              cpu: {{ .Values.api.resources.requests.cpu }}
              memory: {{ .Values.api.resources.requests.memory }}
            limits:
              cpu: {{ .Values.api.resources.limits.cpu }}
              memory: {{ .Values.api.resources.limits.memory }}
