apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ing-{{ .Values.api.app }}
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.api.host }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: {{ .Values.api.svc.name }}
              port:
                number: {{ .Values.api.svc.port }}
              