apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ .Release.Name}}-ing
  namespace: {{ .Values.namespace }}
spec:
  rules:
    - host: {{ .Values.api.host }}
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: {{ .Release.Name}}-{{ .Values.api.svc.name }}-svc
              port:
                number: {{ .Values.api.svc.port }}
              