{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ app }}-svc
  namespace: {{ .Values.common.namespace }}
spec:
  selector:
    app: {{ app }}
  type: ClusterIP
  ports: 
  - name: {{ app }}
    protocol: TCP
    port: {{ port }}
    targetPort: {{ targetPort }}
{{ end }}    