apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: aprenda-golang
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: dexfs/my-api:v1.1.0
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-cm
            - secretRef:
                name: redis
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "512Mi"
